.PHONY: all clean

all:
	make -C RoseBush
	make -C FuzzyDie
	make -C MysteriousRune
	make -C HollyBat
	make -C OrnateMirror
	make -C MimicChest

clean:
	make clean -C RoseBush
	make clean -C FuzzyDie
	make clean -C MysteriousRune
	make clean -C HollyBat
	make clean -C OrnateMirror
	make clean -C MimicChest
