.PHONY: all clean

all:
	make -C RoseBush
	make -C FuzzyDie
	make -C MysteriousRune
	make -C HollyBat

clean:
	make clean -C RoseBush
	make clean -C FuzzyDie
	make clean -C MysteriousRune
	make clean -C HollyBat
